//persons
export const FETCH_LEADERBOARD =  'FETCH_LEADERBOARD';
export const FETCH_LEADERBOARD_SUCCESS =  'FETCH_LEADERBOARD_SUCCESS';
export const FETCH_LEADERBOARD_FAILED =  'FETCH_LEADERBOARD_FAILED';
//routes
export const FETCH_UPLOADED_ROUTES = 'FETCH_UPLOADED_ROUTES';
export const FETCH_UPLOADED_ROUTES_SUCCESS = 'FETCH_UPLOADED_ROUTES_SUCCESS';
export const FETCH_UPLOADED_ROUTES_FAILED = 'FETCH_UPLOADED_ROUTES_FAILED';
//user
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const CHANGE_USER_STORE_SETTINGS = 'CHANGE_USER_STORE_SETTINGS';
//general
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';